export const FINANCIAL_GLOSSARY = {
  DCF: "Discounted Cash Flow - values investments by calculating the present value of future cash flows",
  NPV: "Net Present Value - measures investment value by comparing present value of future cash inflows to investment cost",
  IRR: "Internal Rate of Return - the discount rate at which an investment's NPV equals zero",
  WACC: "Weighted Average Cost of Capital - the blended cost of equity and debt financing used as discount rate",
  CAPEX: "Capital Expenditures - spending on long-term assets like equipment, facilities, or technology",
  OPEX: "Operating Expenses - day-to-day costs of running the business like salaries and rent",
  EBITDA: "Earnings Before Interest, Tax, Depreciation & Amortization - measures operating profitability",
  FCFF: "Free Cash Flow to Firm - cash generated by operations available to all investors after expenses and investments",
  CLV: "Customer Lifetime Value - total profit expected from a customer over their entire relationship with the company",
  LTV: "Customer Lifetime Value - total profit expected from a customer over their entire relationship with the company",
  CAC: "Customer Acquisition Cost - total marketing and sales expense to acquire new customers",
  CAPM: "Capital Asset Pricing Model - calculates required return on equity based on risk",
  "M&A": "Mergers & Acquisitions - transactions where companies combine or are purchased",
  NWC: "Net Working Capital - current assets minus current liabilities needed for operations",
  ROC: "Return on Capital - measures profitability relative to total capital invested"
} as const;

export type GlossaryTerm = keyof typeof FINANCIAL_GLOSSARY;
