// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyvhyrgtrnssmqryiyku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5dmh5cmd0cm5zc21xcnlpeWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NTQ0NzcsImV4cCI6MjA2NzQzMDQ3N30.Va-1XujWBpzV-ITjP6DW8V_Us1e_AQ6CQqXBU6C-4iw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});